const $=s=>document.querySelector(s);let view=new Date(2026,8,1), selected=null;
function iso(d){return d.toISOString().slice(0,10)}
function localDate(y,m,day){return new Date(y,m,day,12)}
function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}
function cycleFor(d){let start=new Date(SCHOOL_YEAR_START+'T12:00:00');let n=0,x=start;while(iso(x)!==iso(d)){if(x.getDay()>=1&&x.getDay()<=5&&!CLOSED_DATES.has(iso(x)))n++;x=addDays(x,1);if(n>250)break}return n%10+1}
function isSchoolDay(d){return d.getDay()>=1&&d.getDay()<=5&&!CLOSED_DATES.has(iso(d))&&d>=new Date(SCHOOL_YEAR_START+'T12:00:00')&&d<=new Date(SCHOOL_YEAR_END+'T12:00:00')}
function freePeriods(d){if(!isSchoolDay(d))return[];let c=cycleFor(d);return PERIODS.filter(p=>!TEACHING[p.id][c-1])}
async function reservations(date){if(API_URL.startsWith('http')){try{let r=await fetch(API_URL+'?action=day&date='+date);return await r.json()}catch(e){}}return {reservations:[]}}
function render(){let y=view.getFullYear(),m=view.getMonth();$('#month').textContent=view.toLocaleDateString('fr-CA',{month:'long',year:'numeric'});let first=localDate(y,m,1),last=new Date(y,m+1,0),grid=$('#calendar');grid.innerHTML='';['L','M','M','J','V','S','D'].forEach(x=>{let e=document.createElement('div');e.className='weekday';e.textContent=x;grid.append(e)});let offset=(first.getDay()+6)%7;for(let i=0;i<offset;i++){let e=document.createElement('div');e.className='day muted';grid.append(e)}for(let n=1;n<=last.getDate();n++){let d=localDate(y,m,n),e=document.createElement('div');e.className='day';if(!isSchoolDay(d))e.classList.add('closed');let fs=freePeriods(d);e.innerHTML=`<div class="num">${n}</div>${isSchoolDay(d)?`<div class="cycle">Jour ${cycleFor(d)}</div><div class="free">${fs.length} période${fs.length>1?'s':''} libre${fs.length>1?'s':''}</div>`:'<div class="cycle">Indisponible</div>'}`;if(selected&&iso(selected)===iso(d))e.classList.add('selected');if(isSchoolDay(d))e.onclick=()=>openSlots(d);grid.append(e)}}
async function openSlots(d){selected=d;render();$('#slots').classList.remove('hidden');$('#selectedDate').textContent=d.toLocaleDateString('fr-CA',{weekday:'long',day:'numeric',month:'long'});let data=await reservations(iso(d));let booked=new Set((data.reservations||[]).map(x=>String(x.period)));$('#slotList').innerHTML='';freePeriods(d).forEach(p=>{let b=booked.has(String(p.id)),row=document.createElement('div');row.className='slot '+(b?'busy':'');row.innerHTML=`<div><strong>Période ${p.id}</strong><br>${p.start} – ${p.end}</div><button ${b?'disabled':''}>${b?'Réservée':'Réserver'}</button>`;if(!b)row.querySelector('button').onclick=()=>openBooking(d,p);$('#slotList').append(row)})}
function openBooking(d,p){$('#booking').classList.remove('hidden');$('#bookingInfo').textContent=`${d.toLocaleDateString('fr-CA',{weekday:'long',day:'numeric',month:'long'})} — période ${p.id}, ${p.start} à ${p.end}`;$('#bookingMsg').textContent='';$('#name').value='';$('#reason').value='';$('#confirm').onclick=async()=>{let name=$('#name').value.trim();if(!name){$('#bookingMsg').textContent='Veuillez inscrire votre nom.';return}if(!API_URL.startsWith('http')){$('#bookingMsg').textContent='Le site est en mode démo. Configurez API_URL dans config.js.';return}$('#confirm').disabled=true;try{let r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'book',date:iso(d),period:p.id,name,reason:$('#reason').value.trim()})});let out=await r.json();if(out.ok){$('#booking').classList.add('hidden');await openSlots(d)}else $('#bookingMsg').textContent=out.error||'Impossible de réserver.'}catch(e){$('#bookingMsg').textContent='Erreur de communication avec le serveur.'}finally{$('#confirm').disabled=false}}}
$('#prev').onclick=()=>{view.setMonth(view.getMonth()-1);render()};
$('#next').onclick=()=>{view.setMonth(view.getMonth()+1);render()};
$('#closeSlots').onclick=()=>$('#slots').classList.add('hidden');
$('#closeBooking').onclick=()=>$('#booking').classList.add('hidden');
$('#adminBtn').onclick=()=>window.location.href='admin.html';
render();
